14-natoma/ADPQ-Prototype/Source/Com.Natoma.Hhs.Prototype.UI/Com.Natoma.HhsPrototype.UserInterface/Controllers/LocationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Com.Natoma.HhsPrototype.UserInterface.Controllers
{
    public class LocationController : HhsPrototypeController
    {
        // GET: Locations
        public ActionResult Index()
        {
            ViewBag.IsUserLoggedIn = this.IsUserLoggedIn;

            if (this.CurrentUser != null && this.CurrentUser.ZipCode != null)
            {
                ViewBag.ZipCode = this.CurrentUser.ZipCode;
            }

            return View();
        }
    }
}

14-natoma/ADPQ-Prototype/Source/Com.Natoma.Hhs.Prototype.UI/Com.Natoma.HhsPrototype.UserInterface/Controllers/UserProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.ServiceModel;

using Com.Natoma.HhsPrototype.UserInterface.Helpers;
using Com.Natoma.HhsPrototype.UserInterface.Models;

namespace Com.Natoma.HhsPrototype.UserInterface.Controllers
{
    public class UserProfileController : HhsPrototypeController
    {
        #region Private Members
        //private ServiceHelper serviceHelper = new ServiceHelper();
        private SelectList yesNoList = new SelectList(new List<SelectListItem>()
        {
            new SelectListItem() { Text = "No", Value = false.ToString() },
            new SelectListItem() { Text = "Yes", Value = true.ToString() }
        }, "Value", "Text", 0);

        private SelectList stateList = new SelectList(new List<SelectListItem>()
        {
            new SelectListItem() { Text = "(Select State)", Value = "" },
            new SelectListItem() {Text="Alabama", Value="AL"},
            new SelectListItem() { Text="Alaska", Value="AK"},
            new SelectListItem() { Text="Arizona", Value="AZ"},
            new SelectListItem() { Text="Arkansas", Value="AR"},
            new SelectListItem() { Text="California", Value="CA"},
            new SelectListItem() { Text="Colorado", Value="CO"},
            new SelectListItem() { Text="Connecticut", Value="CT"},
            new SelectListItem() { Text="District of Columbia", Value="DC"},
            new SelectListItem() { Text="Delaware", Value="DE"},
            new SelectListItem() { Text="Florida", Value="FL"},
            new SelectListItem() { Text="Georgia", Value="GA"},
            new SelectListItem() { Text="Hawaii", Value="HI"},
            new SelectListItem() { Text="Idaho", Value="ID"},
            new SelectListItem() { Text="Illinois", Value="IL"},
            new SelectListItem() { Text="Indiana", Value="IN"},
            new SelectListItem() { Text="Iowa", Value="IA"},
            new SelectListItem() { Text="Kansas", Value="KS"},
            new SelectListItem() { Text="Kentucky", Value="KY"},
            new SelectListItem() { Text="Louisiana", Value="LA"},
            new SelectListItem() { Text="Maine", Value="ME"},
            new SelectListItem() { Text="Maryland", Value="MD"},
            new SelectListItem() { Text="Massachusetts", Value="MA"},
            new SelectListItem() { Text="Michigan", Value="MI"},
            new SelectListItem() { Text="Minnesota", Value="MN"},
            new SelectListItem() { Text="Mississippi", Value="MS"},
            new SelectListItem() { Text="Missouri", Value="MO"},
            new SelectListItem() { Text="Montana", Value="MT"},
            new SelectListItem() { Text="Nebraska", Value="NE"},
            new SelectListItem() { Text="Nevada", Value="NV"},
            new SelectListItem() { Text="New Hampshire", Value="NH"},
            new SelectListItem() { Text="New Jersey", Value="NJ"},
            new SelectListItem() { Text="New Mexico", Value="NM"},
            new SelectListItem() { Text="New York", Value="NY"},
            new SelectListItem() { Text="North Carolina", Value="NC"},
            new SelectListItem() { Text="North Dakota", Value="ND"},
            new SelectListItem() { Text="Ohio", Value="OH"},
            new SelectListItem() { Text="Oklahoma", Value="OK"},
            new SelectListItem() { Text="Oregon", Value="OR"},
            new SelectListItem() { Text="Pennsylvania", Value="PA"},
            new SelectListItem() { Text="Rhode Island", Value="RI"},
            new SelectListItem() { Text="South Carolina", Value="SC"},
            new SelectListItem() { Text="South Dakota", Value="SD"},
            new SelectListItem() { Text="Tennessee", Value="TN"},
            new SelectListItem() { Text="Texas", Value="TX"},
            new SelectListItem() { Text="Utah", Value="UT"},
            new SelectListItem() { Text="Vermont", Value="VT"},
            new SelectListItem() { Text="Virginia", Value="VA"},
            new SelectListItem() { Text="Washington", Value="WA"},
            new SelectListItem() { Text="West Virginia", Value="WV"},
            new SelectListItem() { Text="Wisconsin", Value="WI"},
            new SelectListItem() { Text="Wyoming", Value="WY"}
        }, "Value", "Text", "CA");
        #endregion

        // GET: UserProfile
        public ActionResult Index()
        {
            ViewBag.IsUserLoggedIn = this.IsUserLoggedIn;

            if (!this.IsUserLoggedIn)
            {
                return RedirectToAction("Index", "Home");
            }

            ViewData["yesNoList"] = yesNoList;
            ViewData["stateList"] = stateList;

            string saveSuccessful = "SaveSuccessful";
            if (TempData[saveSuccessful] != null)
            {
                ViewBag.SaveSuccessful = TempData[saveSuccessful];
            }

            return View(CurrentUser);
        }

        [HttpPost]
        public ActionResult Save(UserProfileModel model)
        {
            ViewBag.IsUserLoggedIn = this.IsUserLoggedIn;

            if (!this.IsUserLoggedIn)
            {
                return RedirectToAction("Index", "Home");
            }

            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Invalid fields.  Did not save.");
                TempData["SaveSuccessful"] = false;
                CurrentUser = model;
                return RedirectToAction("Index");
            }

            try
            {
                if (CurrentUser.Uid.HasValue)
                {
                    // RsSet properties that are not displayed on screen and should not
                    // be added to the screen for security purposes
                    model.Uid = CurrentUser.Uid;
                    model.Password = CurrentUser.Password;
                    ServiceManager.UpdateUserProfile(model);
                }
                else
                {
                    model.Uid = ServiceManager.CreateUserProfile(model);
                }

                CurrentUser = model;

                TempData["SaveSuccessful"] = true;
            }
            catch (FaultException e)
            {
                ModelState.AddModelError("", e.Message);
                TempData["SaveSuccessful"] = false;
            }

            return RedirectToAction("Index");
        }
    }
}

14-natoma/ADPQ-Prototype/Source/Com.Natoma.Hhs.Prototype.UI/Com.Natoma.HhsPrototype.UserInterface/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en-us">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - HHS Prototype</title>
    <link rel="shortcut icon" href="~/favicon.ico" />

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/themes/base/css")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/knockout")
    @Scripts.Render("~/bundles/js/base")
    @RenderSection("scripts", required: false)

    <!-- Google Analyitics -->
    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date(); a = s.createElement(o),
            m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
        })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-78680606-1', 'auto');
        ga('send', 'pageview');
    </script>

    <!--
    To collect end-user usage analytics about your application,
    insert the following script into each page you want to track.
    Place this code immediately before the closing </head> tag,
    and before any other scripts. Your first data will appear
    automatically in just a few seconds.
    -->
    <script type="text/javascript">
        var appInsights = window.appInsights || function (config) {
            function r(config) { t[config] = function () { var i = arguments; t.queue.push(function () { t[config].apply(t, i) }) } } var t = { config: config }, u = document, e = window, o = "script", s = u.createElement(o), i, f; for (s.src = config.url || "//az416426.vo.msecnd.net/scripts/a/ai.0.js", u.getElementsByTagName(o)[0].parentNode.appendChild(s), t.cookie = u.cookie, t.queue = [], i = ["Event", "Exception", "Metric", "PageView", "Trace"]; i.length;) r("track" + i.pop()); return r("setAuthenticatedUserContext"), r("clearAuthenticatedUserContext"), config.disableExceptionTracking || (i = "onerror", r("_" + i), f = e[i], e[i] = function (config, r, u, e, o) { var s = f && f(config, r, u, e, o); return s !== !0 && t["_" + i](config, r, u, e, o), s }), t
        }({
            instrumentationKey: "1b46dded-1559-4af9-a5e3-69876d5986db"
        });

        window.appInsights = appInsights;
        appInsights.trackPageView();
    </script>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <a href="#mainContent" class="link-main-content">Skip to Main Content</a>
        </div>
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" aria-label="Navigation Toggle">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="@Url.Action("Index", "Home")" class="navbar-brand"><span class="glyphicon glyphicon-off natoma-icon" aria-hidden="true"></span> HHS Prototype</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (ViewBag.IsUserLoggedIn != null && ViewBag.IsUserLoggedIn)
                    {
                        <li><a href="@Url.Action("Index", "UserProfile")"><span class="glyphicon glyphicon-user natoma-icon" aria-hidden="true"></span> Profile</a></li>
                        <li><a href="@Url.Action("Index", "Message")"><span class="glyphicon glyphicon-envelope natoma-icon" aria-hidden="true"></span> Mailbox</a></li>
                    }
                    <li><a href="@Url.Action("Index", "Location")"><span class="glyphicon glyphicon-globe natoma-icon" aria-hidden="true"></span> Locations</a></li>
                    <li><a href="@Url.Action("About", "Home")"><span class="glyphicon glyphicon-question-sign natoma-icon" aria-hidden="true"></span> About</a></li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div id="mainContent" class="container body-content">
        @RenderBody()
        <hr />
        <footer class="text-center">
            <p><a href="http://www.natomatech.com" target="_blank"><img class="natoma-img-footer" src="~/Images/NT_Logo_rgb_tight_transparent.gif" alt="Natoma Technologies Logo" /></a></p>
            <p>&copy; @DateTime.Now.Year - Natoma Technologies, Inc.</p>
        </footer>
    </div>
</body>
</html>